/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.aiva1.helsinkidata;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class SparkAppTest {
    @Test void appHasAGreeting() {
        SparkApp classUnderTest = new SparkApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
