/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.aiva1.helsinkidata;

public class SparkApp {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new SparkApp().getGreeting());
    }
}
